services:
  postgres:
    build: .
    container_name: postgres_quantum-leap
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quantum-leap
      POSTGRES_USER: gabrielbatista
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: