name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Clean Maven Cache
      run: mvn dependency:purge-local-repository

    - name: Configure Lombok
      run: mvn -DskipTests clean install -Dmaven.javadoc.skip=true -Dspotbugs.skip=true

    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose

    - name: Docker Build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
      env:
        DOCKER_BUILDKIT: 1

    - name: Docker Compose Up
      run: |
        docker-compose up -d
        while ! nc -z postgres 5432; do echo "waiting for postgres..."; sleep 1; done
      env:
        COMPOSE_PROJECT_NAME: "quantum-leap"

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Debug Maven Dependencies
      run: mvn dependency:tree

    - name: Run Tests
      run: mvn test
